version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: auth_mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: authdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth_network

volumes:
  mongodb_data:

networks:
  auth_network:
    driver: bridge
